-   id: git-semver-bump
    name: "Cargo Semantic Versioning"
    description: 'Set semantic version from git tags'
    entry: cargo-git-semver bump
    language: rust
    types: [text, rust]
    exclude: '^.pre-commit-config.yaml$'
    always_run: true
    pass_filenames: false

-   id: git-semver-check-tags
    name: "Cargo Tag Sync - Check Tags"
    description: "Check if release was tagged"
    entry: cargo-git-semver check-tags
    language: rust
    types: [text]
    stages: [pre-commit]
    pass_filenames: false
    always_run: true
